spring:
  profiles:
    include: oauth

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver


  h2:
    console:
      enabled: true